name = "SDHQ Ratings Indicator"
version = "0.3.0"
link = "https://github.com/shelbykleindesign/steamdeckhq-crankshaft-plugin"
source = "https://github.com/shelbykleindesign/steamdeckhq-crankshaft-plugin"

[author]
name = "SDHQ"
link = "https://steamdeckhq.com"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
